services:
  backend:
    container_name: backend_container
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      # - PORT= 8000
      - DATABASE_URL=postgresql://postgres:123456@mydb:5432/mydb
    volumes:
      - ./:/app
      - /app/node_modules
  db:
    image: postgres:17
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
